#!/usr/bin/env bash
#
# Prose gate (ADR-0031): lint the repo's authored markdown against the shared
# house style in ~/.claude/prose.md.
#
# The rules are vendored, not referenced: `.vale.ini` and `.vale/styles/` are
# copies written by ~/.claude/scripts/sync-vale.sh, because a machine-global
# styles directory is invisible to CI and to contributors. Re-sync with:
#
#   ~/.claude/scripts/sync-vale.sh .          # apply
#   ~/.claude/scripts/sync-vale.sh --check .  # report drift, write nothing
#
# CI runs this same script (ci.yml), through the same flake as the dev shell
# (ADR-0008), so a run that passes locally passes there.
set -euo pipefail

cd "$(dirname "$0")/.."

# --- Scope --------------------------------------------------------------------
# Authored prose only. The one exclusion is the per-crate CHANGELOG.md: those are
# generated by release-plz from commit subjects (ADR-0012), so they are not
# authored here and any edit is overwritten at the next release.
#
# Rust doc comments are deliberately out of scope. `.vale.ini` carries a
# `[formats] rs = md` alias, but it stays inert without an `[*.rs]` section —
# extending the gate to rustdoc is a separate decision, not a side effect.
#
# `|| true` on the filter is load-bearing: grep exits 1 when it passes nothing
# through, and under `pipefail` that aborts the script at this assignment with no
# message at all — silently, before the empty-list guard below can explain it.
files=$(git ls-files '*.md' | { grep -v '/CHANGELOG\.md$' || true; })

# --- Assert the check has inputs ---------------------------------------------
# With an empty list, `xargs vale` runs vale with no path arguments, so it lints
# empty stdin, reports "0 errors" and exits 0 — a green check over nothing. That
# bug shipped into ~/.claude's own CI once. Fail loudly instead.
if [ -z "$files" ]; then
  echo "prose-lint: no files matched — the scope filter is wrong, or this is not a checkout." >&2
  exit 1
fi

# --- Lint ---------------------------------------------------------------------
# --no-global: vale otherwise merges a machine-global styles directory on top of
# the vendored one, so a contributor's local run disagrees with CI.
#
# Errors block and warnings do not: vale's exit code counts errors only,
# whatever MinAlertLevel is set to, so no extra flag is needed to get that.
echo "prose-lint: $(printf '%s\n' "$files" | wc -l | tr -d ' ') file(s), vale $(vale --version | awk '{print $3}')"
printf '%s\n' "$files" | xargs vale --no-global --config .vale.ini
